# Generated by Django 4.1.7 on 2023-04-23 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
                ('proyecto', models.IntegerField()),
                ('nombre_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.ficha')),
            ],
        ),
    ]
